### ISSUE TITLE
Available in Bower

### ISSUE THREAD

**Issue by JonasKa** [ismyrnow/Leaflet.groupedlayercontrol#19]
It would be nice if you made it available through Bower.

//Thanks!

**Comment by newmanw** [comment]
+1, love this plugin.

Just looked for this in Bower as well.  Wasn't there :(

**Comment by ismyrnow** [comment]
Good idea. I'll definitely add the capability.

**Comment by vicchi** [comment]
Just opened a pull request to add Bower support (see #21)

**Comment by ismyrnow** [comment]
Thanks @vicchi

**Comment by ismyrnow** [comment]
No available via bower.

```
bower install leaflet-groupedlayercontrol
```
