### ISSUE TITLE
Compatible with CartoDB

### ISSUE THREAD

**Issue by naomikeusch** [ismyrnow/Leaflet.groupedlayercontrol#26]
Hi,
I'm trying to use this plug in with CartoDB layers. I was able to do so with the L.control.layers function, but not with this one... is it possible?
Thanks!

**Comment by ismyrnow** [comment]
Which version of leaflet are you using?

**Comment by naomikeusch** [comment]
0.7.3 do I need to use 1.0?

**Comment by ismyrnow** [comment]
I would assume that so long as the CartoDB layer extends the standard leaflet layer type, it should work. Can you provide examples of it working with the leaflet layer control and not working with the grouped one (on [jsbin](http://jsbin.com) or the like)?
