### ISSUE TITLE
groupCheckboxes not working in the min version?

### ISSUE THREAD

**Issue by HeikkiVesanto** [ismyrnow/Leaflet.groupedlayercontrol#28]
Hi I could not get the "groupCheckboxes: true" option to work when using the "min" version from the dist folder.

Using the version from the src folder it worked as intended without any changes.

**Comment by ismyrnow** [comment]
The PR for the feature didn't include the minified version. Thanks for the catch.

I've rebuilt those files and updated the plugin to v0.4.0.
