### ISSUE TITLE
Add Off item for exclusive radio groups

### ISSUE THREAD

**Issue by spydmobile** [ismyrnow/Leaflet.groupedlayercontrol#31]
Lets say you have a group that is exclusive, but you want it to have a none option. there is no good way to do this without throwing errors.

**Comment by jdoblas** [comment]
I'm with spydmobile on this one, it will be quite helpful to have at least a toggle button next to the exclusive group name.

**Comment by ismyrnow** [comment]
Ah, a limitation of radio inputs. You could probably create an empty layer group to act as your none option. For example:

```javascript
var noneLayer = L.layerGroup();
```

I haven't tried this, but I don't suspect it will throw an error.
