### ISSUE TITLE
How can I use this plugin with no base layer?

### ISSUE THREAD

**Issue by spydmobile** [ismyrnow/Leaflet.groupedlayercontrol#36]
Thanks for this great plugin! But I have tried all kinds of ways to use this plugin without base layers , I have another control managing the base layers, can you add the ability to use no base layer?

**Comment by geospatialem** [comment]
Is [this example](http://geospatialem.github.io/leaflet-interactive-template) what you are trying to implement (only showing the `groupedOverlays`/`options` in the control)? 

Have you tried declaring the `baseLayers` variable, but leaving it empty?

For example:  
```
var baseLayers = {
};
```

**Comment by dosstx** [comment]
Yes, you can do: `L.control.groupedLayers(null, overlays, options).addTo(map);`

**Comment by spydmobile** [comment]
I am sorry, both of these work, and my application is working now. the error was actually cased by a misconfiguration of my overlays which caused me to think my empty baselayer object or use of null was causing errors. Thanks  both of you.
