### ISSUE TITLE
removeLayer() doesnt remove layer from the map control only removed from the group layer control

### ISSUE THREAD

**Issue by ChrisCSmith** [ismyrnow/Leaflet.groupedlayercontrol#5]
when calling 
layerControl.removeLayer(layer);
the layer is removed from the control but not from the map, 
the following code appears to fix it...

 removeLayer: function (layer) {
    var id = L.Util.stamp(layer);
/_Start inserted code_/
    var obj = this._layers[id];
    if (obj && this._map.hasLayer(obj.layer)) {
        this._map.removeLayer(obj.layer);
    }
/_End inserted code_/
    delete this._layers[id];
    this._domGroups.length=0;
    this._update();

```
return this;
```

  }

**Comment by water42** [comment]
Thanks for the function @ChrisCSmith
